"""Service for creating pages."""

import re

from src.core.commands.page_commands import CreatePageCommand
from src.core.common.result import Result
from src.core.domain.page import Page
from src.core.interfaces.repositories import IPageRepository


def extract_plain_text(markdown_content: str) -> str:
    """Extract plain text from markdown for search indexing."""
    text = markdown_content
    text = re.sub(r'```[\s\S]*?```', '', text)  # Remove code blocks
    text = re.sub(r'`[^`]*`', '', text)  # Remove inline code
    text = re.sub(r'\[([^\]]+)\]\([^\)]+\)', r'\1', text)  # Remove links but keep text
    text = re.sub(r'!\[([^\]]*)\]\([^\)]+\)', '', text)  # Remove images
    text = re.sub(r'^#+\s+', '', text, flags=re.MULTILINE)  # Remove headers
    text = re.sub(r'[*_]{1,2}([^*_]+)[*_]{1,2}', r'\1', text)  # Remove bold/italic
    return text.strip()


class CreatePageService:
    """Service to handle page creation business logic."""
    
    def __init__(self, page_repository: IPageRepository):
        """
        Initialize the service.
        
        Args:
            page_repository: Repository for page persistence.
        """
        self.page_repository = page_repository
    
    async def execute(self, command: CreatePageCommand) -> Result[Page]:
        """
        Execute the create page command.
        
        Args:
            command: The create page command.
            
        Returns:
            Result containing the created page or error information.
        """
        # Extract plain text for search
        content_plain = extract_plain_text(command.content)
        
        # Create domain entity
        page = Page(
            id="",  # Will be generated by repository
            section_id=command.section_id,
            title=command.title.strip(),
            content=command.content,
            content_plain=content_plain,
            parent_page_id=command.parent_page_id,
            display_order=command.display_order
        )
        
        # Validate domain rules
        is_valid, error_msg = page.validate()
        if not is_valid:
            return Result.fail(f"Validation failed: {error_msg}")
        
        # Persist
        try:
            created_page = await self.page_repository.create(page)
            return Result.ok(created_page, "Page created successfully")
        except Exception as e:
            return Result.fail(f"Failed to create page: {str(e)}")
