"""Service for creating notebooks."""

from src.core.commands.notebook_commands import CreateNotebookCommand
from src.core.common.result import Result
from src.core.domain.notebook import Notebook
from src.core.interfaces.repositories import INotebookRepository


class CreateNotebookService:
    """Service to handle notebook creation business logic."""
    
    def __init__(self, notebook_repository: INotebookRepository):
        """
        Initialize the service.
        
        Args:
            notebook_repository: Repository for notebook persistence.
        """
        self.notebook_repository = notebook_repository
    
    async def execute(self, command: CreateNotebookCommand) -> Result[Notebook]:
        """
        Execute the create notebook command.
        
        Args:
            command: The create notebook command.
            
        Returns:
            Result containing the created notebook or error information.
        """
        # Create domain entity
        notebook = Notebook(
            id="",  # Will be generated by repository
            name=command.name.strip(),
            color=command.color
        )
        
        # Validate domain rules
        is_valid, error_msg = notebook.validate()
        if not is_valid:
            return Result.fail(f"Validation failed: {error_msg}")
        
        # Persist
        try:
            created_notebook = await self.notebook_repository.create(notebook)
            return Result.ok(created_notebook, "Notebook created successfully")
        except Exception as e:
            return Result.fail(f"Failed to create notebook: {str(e)}")
