"""Service for creating sections."""

from src.core.commands.section_commands import CreateSectionCommand
from src.core.common.result import Result
from src.core.domain.section import Section
from src.core.interfaces.repositories import ISectionRepository


class CreateSectionService:
    """Service to handle section creation business logic."""
    
    def __init__(self, section_repository: ISectionRepository):
        """
        Initialize the service.
        
        Args:
            section_repository: Repository for section persistence.
        """
        self.section_repository = section_repository
    
    async def execute(self, command: CreateSectionCommand) -> Result[Section]:
        """
        Execute the create section command.
        
        Args:
            command: The create section command.
            
        Returns:
            Result containing the created section or error information.
        """
        # Create domain entity
        section = Section(
            id="",  # Will be generated by repository
            notebook_id=command.notebook_id,
            name=command.name.strip(),
            display_order=command.display_order
        )
        
        # Validate domain rules
        is_valid, error_msg = section.validate()
        if not is_valid:
            return Result.fail(f"Validation failed: {error_msg}")
        
        # Persist
        try:
            created_section = await self.section_repository.create(section)
            return Result.ok(created_section, "Section created successfully")
        except Exception as e:
            return Result.fail(f"Failed to create section: {str(e)}")
